apiVersion: v2
name: kgateway
description: A minimal Helm chart that deploys the Gloo Gateway with Kubernetes Gateway API integration.
type: application

version: 1.0.0
appVersion: "1.0.0"
keywords:
  - apigateway
  - kubernetes
  - gateway
  - gatewayapi

sources:
  - https://github.com/solo-io/gloo