# TODO(tim): Does this need to be a composite action?
name: Conformance Tests
description: run kubernetes gateway api conformance tests
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Setup Go
    uses: actions/setup-go@v5
    with:
      go-version-file: go.mod
  - uses: azure/setup-kubectl@v4
    id: kubectl
    with:
      version: ${{ matrix.kube-version.kubectl }}
  - name: Run the kubernetes gateway API conformance tests
    shell: bash
    run: make conformance
  - name: Capture debug information when tests fail
    if: ${{ failure() }}
    shell: bash
    run: |
      kubectl -n kgateway-system get events --sort-by='{.lastTimestamp}'
      echo
      kubectl -n gateway-conformance-infra get events --sort-by='{.lastTimestamp}'
      echo
      kubectl -n gateway-conformance-app-backend get events --sort-by='{.lastTimestamp}'
      echo
      kubectl -n gateway-conformance-web-backend get events --sort-by='{.lastTimestamp}'
      echo
      kubectl -n kgateway-system logs deploy/kgateway
  - name: Upload reports
    if: ${{ failure() }}
    uses: ./.github/actions/upload-artifact
    with:
      # Name of the path to upload. The VERSION variable refers to the Makefile
      # VERSION variable.
      name: conformance-kgateway-gateway-report@k8s${{ matrix.kube-version.kubectl }}
      path: _test/conformance/${{ env.VERSION }}-report.yaml
