// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AwsAuthApplyConfiguration represents a declarative configuration of the AwsAuth type for use
// with apply.
type AwsAuthApplyConfiguration struct {
	IRSA   *AWSAuthIRSAApplyConfiguration            `json:"irsa,omitempty"`
	Secret *AWSAuthSecretReferenceApplyConfiguration `json:"secret,omitempty"`
}

// AwsAuthApplyConfiguration constructs a declarative configuration of the AwsAuth type for use with
// apply.
func AwsAuth() *AwsAuthApplyConfiguration {
	return &AwsAuthApplyConfiguration{}
}

// WithIRSA sets the IRSA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IRSA field is set to the value of the last call.
func (b *AwsAuthApplyConfiguration) WithIRSA(value *AWSAuthIRSAApplyConfiguration) *AwsAuthApplyConfiguration {
	b.IRSA = value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *AwsAuthApplyConfiguration) WithSecret(value *AWSAuthSecretReferenceApplyConfiguration) *AwsAuthApplyConfiguration {
	b.Secret = value
	return b
}
