// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AWSAuthSecretReferenceApplyConfiguration represents a declarative configuration of the AWSAuthSecretReference type for use
// with apply.
type AWSAuthSecretReferenceApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// AWSAuthSecretReferenceApplyConfiguration constructs a declarative configuration of the AWSAuthSecretReference type for use with
// apply.
func AWSAuthSecretReference() *AWSAuthSecretReferenceApplyConfiguration {
	return &AWSAuthSecretReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AWSAuthSecretReferenceApplyConfiguration) WithName(value string) *AWSAuthSecretReferenceApplyConfiguration {
	b.Name = &value
	return b
}
