// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AwsLambdaUpstreamApplyConfiguration represents a declarative configuration of the AwsLambdaUpstream type for use
// with apply.
type AwsLambdaUpstreamApplyConfiguration struct {
	FunctionName *string `json:"functionName,omitempty"`
	Qualifier    *string `json:"qualifier,omitempty"`
}

// AwsLambdaUpstreamApplyConfiguration constructs a declarative configuration of the AwsLambdaUpstream type for use with
// apply.
func AwsLambdaUpstream() *AwsLambdaUpstreamApplyConfiguration {
	return &AwsLambdaUpstreamApplyConfiguration{}
}

// WithFunctionName sets the FunctionName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FunctionName field is set to the value of the last call.
func (b *AwsLambdaUpstreamApplyConfiguration) WithFunctionName(value string) *AwsLambdaUpstreamApplyConfiguration {
	b.FunctionName = &value
	return b
}

// WithQualifier sets the Qualifier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Qualifier field is set to the value of the last call.
func (b *AwsLambdaUpstreamApplyConfiguration) WithQualifier(value string) *AwsLambdaUpstreamApplyConfiguration {
	b.Qualifier = &value
	return b
}
