// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// UpstreamSpecApplyConfiguration represents a declarative configuration of the UpstreamSpec type for use
// with apply.
type UpstreamSpecApplyConfiguration struct {
	Type   *string                           `json:"type,omitempty"`
	Aws    *AwsUpstreamApplyConfiguration    `json:"aws,omitempty"`
	Static *StaticUpstreamApplyConfiguration `json:"static,omitempty"`
}

// UpstreamSpecApplyConfiguration constructs a declarative configuration of the UpstreamSpec type for use with
// apply.
func UpstreamSpec() *UpstreamSpecApplyConfiguration {
	return &UpstreamSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *UpstreamSpecApplyConfiguration) WithType(value string) *UpstreamSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithAws sets the Aws field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Aws field is set to the value of the last call.
func (b *UpstreamSpecApplyConfiguration) WithAws(value *AwsUpstreamApplyConfiguration) *UpstreamSpecApplyConfiguration {
	b.Aws = value
	return b
}

// WithStatic sets the Static field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Static field is set to the value of the last call.
func (b *UpstreamSpecApplyConfiguration) WithStatic(value *StaticUpstreamApplyConfiguration) *UpstreamSpecApplyConfiguration {
	b.Static = value
	return b
}
