// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// FakeBackends implements BackendInterface
type FakeBackends struct {
	Fake *FakeGatewayV1alpha1
	ns   string
}

var backendsResource = v1alpha1.SchemeGroupVersion.WithResource("backends")

var backendsKind = v1alpha1.SchemeGroupVersion.WithKind("Backend")

// Get takes name of the backend, and returns the corresponding backend object, and an error if there is any.
func (c *FakeBackends) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Backend, err error) {
	emptyResult := &v1alpha1.Backend{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(backendsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Backend), err
}

// List takes label and field selectors, and returns the list of Backends that match those selectors.
func (c *FakeBackends) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BackendList, err error) {
	emptyResult := &v1alpha1.BackendList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(backendsResource, backendsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BackendList{ListMeta: obj.(*v1alpha1.BackendList).ListMeta}
	for _, item := range obj.(*v1alpha1.BackendList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backends.
func (c *FakeBackends) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(backendsResource, c.ns, opts))

}

// Create takes the representation of a backend and creates it.  Returns the server's representation of the backend, and an error, if there is any.
func (c *FakeBackends) Create(ctx context.Context, backend *v1alpha1.Backend, opts v1.CreateOptions) (result *v1alpha1.Backend, err error) {
	emptyResult := &v1alpha1.Backend{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(backendsResource, c.ns, backend, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Backend), err
}

// Update takes the representation of a backend and updates it. Returns the server's representation of the backend, and an error, if there is any.
func (c *FakeBackends) Update(ctx context.Context, backend *v1alpha1.Backend, opts v1.UpdateOptions) (result *v1alpha1.Backend, err error) {
	emptyResult := &v1alpha1.Backend{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(backendsResource, c.ns, backend, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Backend), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackends) UpdateStatus(ctx context.Context, backend *v1alpha1.Backend, opts v1.UpdateOptions) (result *v1alpha1.Backend, err error) {
	emptyResult := &v1alpha1.Backend{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(backendsResource, "status", c.ns, backend, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Backend), err
}

// Delete takes name of the backend and deletes it. Returns an error if one occurs.
func (c *FakeBackends) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(backendsResource, c.ns, name, opts), &v1alpha1.Backend{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackends) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(backendsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BackendList{})
	return err
}

// Patch applies the patch and returns the patched backend.
func (c *FakeBackends) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Backend, err error) {
	emptyResult := &v1alpha1.Backend{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(backendsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Backend), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied backend.
func (c *FakeBackends) Apply(ctx context.Context, backend *apiv1alpha1.BackendApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Backend, err error) {
	if backend == nil {
		return nil, fmt.Errorf("backend provided to Apply must not be nil")
	}
	data, err := json.Marshal(backend)
	if err != nil {
		return nil, err
	}
	name := backend.Name
	if name == nil {
		return nil, fmt.Errorf("backend.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.Backend{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(backendsResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Backend), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeBackends) ApplyStatus(ctx context.Context, backend *apiv1alpha1.BackendApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Backend, err error) {
	if backend == nil {
		return nil, fmt.Errorf("backend provided to Apply must not be nil")
	}
	data, err := json.Marshal(backend)
	if err != nil {
		return nil, err
	}
	name := backend.Name
	if name == nil {
		return nil, fmt.Errorf("backend.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.Backend{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(backendsResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Backend), err
}
