// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
)

// BackendsGetter has a method to return a BackendInterface.
// A group's client should implement this interface.
type BackendsGetter interface {
	Backends(namespace string) BackendInterface
}

// BackendInterface has methods to work with Backend resources.
type BackendInterface interface {
	Create(ctx context.Context, backend *v1alpha1.Backend, opts v1.CreateOptions) (*v1alpha1.Backend, error)
	Update(ctx context.Context, backend *v1alpha1.Backend, opts v1.UpdateOptions) (*v1alpha1.Backend, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, backend *v1alpha1.Backend, opts v1.UpdateOptions) (*v1alpha1.Backend, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Backend, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BackendList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Backend, err error)
	Apply(ctx context.Context, backend *apiv1alpha1.BackendApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Backend, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, backend *apiv1alpha1.BackendApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Backend, err error)
	BackendExpansion
}

// backends implements BackendInterface
type backends struct {
	*gentype.ClientWithListAndApply[*v1alpha1.Backend, *v1alpha1.BackendList, *apiv1alpha1.BackendApplyConfiguration]
}

// newBackends returns a Backends
func newBackends(c *GatewayV1alpha1Client, namespace string) *backends {
	return &backends{
		gentype.NewClientWithListAndApply[*v1alpha1.Backend, *v1alpha1.BackendList, *apiv1alpha1.BackendApplyConfiguration](
			"backends",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.Backend { return &v1alpha1.Backend{} },
			func() *v1alpha1.BackendList { return &v1alpha1.BackendList{} }),
	}
}
