apiVersion: v1
kind: Service
metadata:
  name: {{ include "kgateway.fullname" . }}
  labels:
    {{- include "kgateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: grpc-xds
    port: 9977
    protocol: TCP
    targetPort: 9977
  selector:
    {{- include "kgateway.selectorLabels" . | nindent 4 }}
