apiVersion: v1
kind: Service
metadata:
  name: kgateway-controller
  namespace: kgateway-system
  labels:
    {{- include "kgateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9443
      name: metrics
      targetPort: 9443
  selector:
    app: "kgateway-controller"