{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kgateway.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kgateway.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kgateway-controller
subjects:
- kind: ServiceAccount
  name: {{ include "kgateway.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: k8sgw-controller
  apiGroup: rbac.authorization.k8s.io
